[lint.per-file-ignores]
"__init__.py" = ["F401"]

[lint]
select = [
    "D",
    "C90",
    "E",
    "W",
    "F",
    "I",
    "B",
    "SIM"
    ]
ignore = ["D415"]

[lint.pydocstyle]
convention = "google"

[lint.mccabe]
max-complexity = 10
